using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using RestaurantManagement.Application.Common.Exceptions;
using RestaurantManagement.Application.Common.Interfaces;
using RestaurantManagement.Application.Features.Modifiers;
using RestaurantManagement.Application.Features.Orders;
using RestaurantManagement.Application.Features.Pricing;
using RestaurantManagement.Domain.Entities;
using RestaurantManagement.Domain.Enums;
using RestaurantManagement.Infrastructure.Persistence.DbContext;
using RestaurantManagement.Infrastructure.Services;
using DomainApplicationException = RestaurantManagement.Application.Common.Exceptions.ApplicationException;

namespace RestaurantManagement.Tests.Orders;

public sealed class OrderManagementServiceTests
{
    [Fact] public async Task Create_dine_in_order_allocates_table() { var (s, c, b, t) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C); order.Status.Should().Be(OrderStatus.Open); (await c.OrderTableAllocations.AnyAsync(x => x.OrderId == order.Id)).Should().BeTrue(); }
    [Fact] public async Task Create_takeaway_order_without_table() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); order.DiningTableId.Should().BeNull(); }
    [Fact] public async Task Create_delivery_requires_address() { var validator = new CreateOrderValidator(); validator.Validate(new CreateOrderRequest(Guid.NewGuid(), OrderType.Delivery, null, null, null, null, null, null)).IsValid.Should().BeFalse(); }
    [Fact] public async Task Order_number_is_server_generated_and_unique() { var (s, _, b, _) = Setup(true); var a = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var z = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); a.OrderNumber.Should().NotBe(z.OrderNumber); a.OrderNumber.Should().StartWith("ORD-"); }
    [Fact] public async Task Invalid_branch_is_rejected() { var (s, _, _, _) = Setup(true); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(Guid.NewGuid(), OrderType.Takeaway, null, null, null, null, null, null), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Unauthorized_branch_is_rejected() { var (s, _, b, _) = Setup(false); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C)).Should().ThrowAsync<ForbiddenException>(); }
    [Fact] public async Task Table_from_another_branch_is_rejected() { var (s, c, b, _) = Setup(true); var other = new Branch { Code = "B2", Name = "Other" }; c.Branches.Add(other); var table = new DiningTable { BranchId = other.Id, AreaId = Guid.NewGuid(), TableNumber = "2", Capacity = 2 }; c.DiningTables.Add(table); await c.SaveChangesAsync(); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, table.Id, null, null, null, null, null), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Out_of_service_table_is_rejected() { var (s, c, b, t) = Setup(true); t.Status = TableStatus.OutOfService; await c.SaveChangesAsync(); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Add_product_uses_authoritative_price() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 2, [], null, order.Version), C); result!.Subtotal.Should().Be(60000); result.Items.Single().UnitPrice.Should().Be(30000); }
    [Fact] public async Task Inactive_product_is_rejected() { var (s, c, b, _) = Setup(true); c.Products.Single().IsActive = false; await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Unavailable_branch_product_is_rejected() { var (s, c, b, _) = Setup(true); c.BranchProducts.Single().IsAvailable = false; await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Variant_snapshot_and_price_are_stored() { var (s, c, b, _) = Setup(true); var variant = new ProductVariant { ProductId = ProductId, Name = "Large", DefaultPrice = 40000 }; c.ProductVariants.Add(variant); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, variant.Id, null, 1, [], null, order.Version), C); result!.Items.Single().VariantNameSnapshot.Should().Be("Large"); result.Items.Single().UnitPrice.Should().Be(40000); }
    [Fact] public async Task Variant_from_another_product_is_rejected() { var (s, c, b, _) = Setup(true); var other = new Product { Sku = "OTHER", Name = "Other" }; c.Products.Add(other); var variant = new ProductVariant { ProductId = other.Id, Name = "Large", DefaultPrice = 1 }; c.ProductVariants.Add(variant); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, variant.Id, null, 1, [], null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Quantity_must_be_positive() => new AddOrderItemValidator().Validate(new AddOrderItemRequest(ProductId, null, null, 0, [], null, null)).IsValid.Should().BeFalse();
    [Fact] public async Task Modifier_price_and_snapshot_are_stored() { var (s, c, b, _) = Setup(true); var group = new ModifierGroup { Name = "Toppings", MinimumSelections = 0, MaximumSelections = 2 }; var modifier = new Modifier { ModifierGroupId = group.Id, Name = "Pearl", DefaultPrice = 5000 }; c.ModifierGroups.Add(group); c.Modifiers.Add(modifier); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = ProductId, ModifierGroupId = group.Id }); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [modifier.Id], null, order.Version), C); result!.Items.Single().Modifiers.Single().ModifierNameSnapshot.Should().Be("Pearl"); result.Items.Single().UnitPrice.Should().Be(35000); }
    [Fact] public async Task Required_modifier_is_enforced() { var (s, c, b, _) = Setup(true); var group = new ModifierGroup { Name = "Size", SelectionType = ModifierSelectionType.Single, IsRequired = true, MinimumSelections = 1, MaximumSelections = 1 }; c.ModifierGroups.Add(group); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = ProductId, ModifierGroupId = group.Id }); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Too_many_modifiers_are_rejected() { var (s, c, b, _) = Setup(true); var group = new ModifierGroup { Name = "T", MaximumSelections = 1 }; var a = new Modifier { ModifierGroupId = group.Id, Name = "A", DefaultPrice = 1 }; var z = new Modifier { ModifierGroupId = group.Id, Name = "Z", DefaultPrice = 1 }; c.ModifierGroups.Add(group); c.Modifiers.AddRange(a, z); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = ProductId, ModifierGroupId = group.Id }); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [a.Id, z.Id], null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Combo_snapshot_is_stored() { var (s, c, b, _) = Setup(true); var combo = new Combo { Code = "C1", Name = "Meal", DefaultPrice = 70000 }; c.Combos.Add(combo); c.ComboItems.Add(new ComboItem { ComboId = combo.Id, ProductId = ProductId, Quantity = 1 }); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(null, null, combo.Id, 1, [], null, order.Version), C); result!.Items.Single().ComboNameSnapshot.Should().Be("Meal"); result.Items.Single().UnitPrice.Should().Be(70000); }
    [Fact] public async Task Inactive_combo_is_rejected() { var (s, c, b, _) = Setup(true); var combo = new Combo { Code = "C1", Name = "Meal", DefaultPrice = 70000, IsActive = false }; c.Combos.Add(combo); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(null, null, combo.Id, 1, [], null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Update_item_recalculates_total() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var item = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C); var updated = await s.UpdateItemAsync(order.Id, item!.Items.Single().Id, new UpdateOrderItemRequest(ProductId, null, null, 3, [], "updated", item.Version), C); updated!.Subtotal.Should().Be(90000); }
    [Fact] public async Task Remove_item_recalculates_total() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var item = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C); var updated = await s.RemoveItemAsync(order.Id, item!.Items.Single().Id, item.Version, C); updated!.Items.Should().BeEmpty(); updated.TotalAmount.Should().Be(0); }
    [Fact] public async Task Status_history_is_created() { var (s, c, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, "confirm", order.Version), C); (await c.OrderStatusHistories.CountAsync(x => x.OrderId == order.Id)).Should().Be(2); }
    [Fact] public async Task Invalid_status_transition_rejected() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Completed, null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Cancellation_requires_valid_state_and_keeps_order() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var cancelled = await s.CancelAsync(order.Id, new CancelOrderRequest("Customer changed mind", order.Version), C); cancelled!.Status.Should().Be(OrderStatus.Cancelled); (await s.GetAsync(order.Id, C)).Should().NotBeNull(); }
    [Fact] public async Task Completed_order_cannot_be_cancelled() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C); var preparing = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Preparing, null, confirmed!.Version), C); var ready = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Ready, null, preparing!.Version), C); var completed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Completed, null, ready!.Version), C); await FluentActions.Awaiting(() => s.CancelAsync(order.Id, new CancelOrderRequest("late", completed!.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Dine_in_completion_releases_table() { var (s, c, b, t) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C); var preparing = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Preparing, null, confirmed!.Version), C); var ready = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Ready, null, preparing!.Version), C); await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Completed, null, ready!.Version), C); (await c.DiningTables.FindAsync(t.Id))!.Status.Should().Be(TableStatus.Available); }
    [Fact] public async Task Active_table_order_conflicts() { var (s, _, b, t) = Setup(true); await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C)).Should().ThrowAsync<ConflictException>(); }
    [Fact] public async Task Stale_version_returns_conflict() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version + 1), C)).Should().ThrowAsync<ConflictException>(); }
    [Fact] public async Task Notes_are_preserved() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, "No ice"), C); (await s.GetAsync(order.Id, C))!.Notes.Should().Be("No ice"); }
    [Fact] public async Task Customer_snapshot_is_preserved() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, "Guest", "0900", null, null), C); var details = await s.GetAsync(order.Id, C); details!.CustomerNameSnapshot.Should().Be("Guest"); details.CustomerPhoneSnapshot.Should().Be("0900"); }
    [Fact] public async Task Branch_listing_is_scoped() { var (s, _, b, _) = Setup(true); await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); (await s.GetBranchOrdersAsync(b.Id, C)).Should().ContainSingle(); }
    [Fact] public async Task Client_price_is_not_accepted_by_request_model() { typeof(AddOrderItemRequest).GetProperty("UnitPrice").Should().BeNull(); }
    [Fact] public async Task Takeaway_does_not_change_table() { var (s, c, b, t) = Setup(true); await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); (await c.DiningTables.FindAsync(t.Id))!.Status.Should().Be(TableStatus.Available); }
    [Fact] public async Task Delivery_snapshot_is_preserved() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Delivery, null, null, null, null, "Address", null), C); (await s.GetAsync(order.Id, C))!.DeliveryAddressSnapshot.Should().Be("Address"); }
    [Fact] public async Task Order_item_note_is_preserved() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], "Less sugar", order.Version), C); result!.Items.Single().Notes.Should().Be("Less sugar"); }
    [Fact] public async Task Order_total_equals_subtotal_without_discounts() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 2, [], null, order.Version), C); result!.TotalAmount.Should().Be(result.Subtotal); result.DiscountAmount.Should().Be(0); result.TaxAmount.Should().Be(0); }
    [Fact] public async Task Open_order_can_confirm() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); (await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C))!.Status.Should().Be(OrderStatus.Confirmed); }
    [Fact] public async Task Confirmed_order_can_prepare() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C); (await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Preparing, null, confirmed!.Version), C))!.Status.Should().Be(OrderStatus.Preparing); }
    [Fact] public async Task Preparing_order_can_ready() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C); var preparing = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Preparing, null, confirmed!.Version), C); (await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Ready, null, preparing!.Version), C))!.Status.Should().Be(OrderStatus.Ready); }
    [Fact] public async Task Ready_order_can_complete() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C); var preparing = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Preparing, null, confirmed!.Version), C); var ready = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Ready, null, preparing!.Version), C); (await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Completed, null, ready!.Version), C))!.Status.Should().Be(OrderStatus.Completed); }
    [Fact] public async Task Completed_order_cannot_add_items() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C); var preparing = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Preparing, null, confirmed!.Version), C); var ready = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Ready, null, preparing!.Version), C); var complete = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Completed, null, ready!.Version), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, complete!.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Inactive_table_is_rejected() { var (s, c, b, t) = Setup(true); t.IsActive = false; await c.SaveChangesAsync(); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Historical_order_remains_after_cancel() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await s.CancelAsync(order.Id, new CancelOrderRequest("cancel", order.Version), C); (await s.GetBranchOrdersAsync(b.Id, C)).Should().ContainSingle(); }
    [Fact] public async Task Product_name_snapshot_is_saved() { var (s, c, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C); c.Products.Single().Name = "Renamed"; await c.SaveChangesAsync(); result!.Items.Single().ProductNameSnapshot.Should().Be("Coffee"); }
    [Fact] public async Task Modifier_selection_from_unassigned_group_rejected() { var (s, c, b, _) = Setup(true); var g = new ModifierGroup { Name = "Other", MaximumSelections = 1 }; var m = new Modifier { ModifierGroupId = g.Id, Name = "x", DefaultPrice = 1 }; c.ModifierGroups.Add(g); c.Modifiers.Add(m); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [m.Id], null, order.Version), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Branch_access_is_checked_on_read() { var (s, _, b, _) = Setup(false); await FluentActions.Awaiting(() => s.GetBranchOrdersAsync(b.Id, C)).Should().ThrowAsync<ForbiddenException>(); }
    [Fact] public async Task Order_version_increments_on_item_add() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C); result!.Version.Should().BeGreaterThan(order.Version); }
    [Fact] public async Task Empty_order_can_be_cancelled() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); (await s.CancelAsync(order.Id, new CancelOrderRequest("empty", order.Version), C))!.Status.Should().Be(OrderStatus.Cancelled); }
    [Fact] public async Task Order_item_modifier_snapshot_price_is_authoritative() { var (s, c, b, _) = Setup(true); var g = new ModifierGroup { Name = "T", MaximumSelections = 1 }; var m = new Modifier { ModifierGroupId = g.Id, Name = "x", DefaultPrice = 5000 }; c.ModifierGroups.Add(g); c.Modifiers.Add(m); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = ProductId, ModifierGroupId = g.Id }); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [m.Id], null, order.Version), C); m.DefaultPrice = 10000; result!.Items.Single().Modifiers.Single().UnitPrice.Should().Be(5000); }
    [Fact] public async Task Confirmed_order_can_be_cancelled() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, order.Version), C); (await s.CancelAsync(order.Id, new CancelOrderRequest("changed", confirmed!.Version), C))!.Status.Should().Be(OrderStatus.Cancelled); }
    [Fact] public async Task Draft_status_is_not_exposed_after_create() { var (s, _, b, _) = Setup(true); (await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C)).Status.Should().Be(OrderStatus.Open); }
    [Fact] public async Task Order_listing_is_empty_for_new_branch() { var (s, _, b, _) = Setup(true); (await s.GetBranchOrdersAsync(b.Id, C)).Should().BeEmpty(); }
    [Fact] public async Task Delivery_order_does_not_require_table() { var (s, _, b, _) = Setup(true); (await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Delivery, null, null, null, null, "A", null), C)).DiningTableId.Should().BeNull(); }
    [Fact] public async Task Dine_in_order_requires_table() { var (s, _, b, _) = Setup(true); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, null, null, null, null, null, null), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Two_orders_cannot_use_same_active_table() { var (s, _, b, t) = Setup(true); await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C); await FluentActions.Awaiting(() => s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.DineIn, t.Id, null, null, null, null, null), C)).Should().ThrowAsync<ConflictException>(); }
    [Fact] public async Task Order_number_is_not_client_supplied() { typeof(CreateOrderRequest).GetProperty("OrderNumber").Should().BeNull(); }
    [Fact] public async Task Update_item_preserves_new_note() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var item = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C); (await s.UpdateItemAsync(order.Id, item!.Items.Single().Id, new UpdateOrderItemRequest(ProductId, null, null, 1, [], "updated note", item.Version), C))!.Items.Single().Notes.Should().Be("updated note"); }
    [Fact] public async Task Item_modifier_quantity_is_one_for_selected_option() { var (s, c, b, _) = Setup(true); var g = new ModifierGroup { Name = "T", MaximumSelections = 1 }; var m = new Modifier { ModifierGroupId = g.Id, Name = "x", DefaultPrice = 1 }; c.ModifierGroups.Add(g); c.Modifiers.Add(m); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = ProductId, ModifierGroupId = g.Id }); await c.SaveChangesAsync(); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var result = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [m.Id], null, order.Version), C); result!.Items.Single().Modifiers.Single().Quantity.Should().Be(1); }
    [Fact] public async Task Order_status_history_keeps_reason() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); await s.CancelAsync(order.Id, new CancelOrderRequest("customer request", order.Version), C); (await s.GetAsync(order.Id, C))!.Status.Should().Be(OrderStatus.Cancelled); }
    [Fact] public async Task Completed_order_cannot_remove_item() { var (s, _, b, _) = Setup(true); var order = await s.CreateAsync(new CreateOrderRequest(b.Id, OrderType.Takeaway, null, null, null, null, null, null), C); var item = await s.AddItemAsync(order.Id, new AddOrderItemRequest(ProductId, null, null, 1, [], null, order.Version), C); var confirmed = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Confirmed, null, item!.Version), C); var preparing = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Preparing, null, confirmed!.Version), C); var ready = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Ready, null, preparing!.Version), C); var complete = await s.ChangeStatusAsync(order.Id, new ChangeOrderStatusRequest(OrderStatus.Completed, null, ready!.Version), C); await FluentActions.Awaiting(() => s.RemoveItemAsync(order.Id, item.Items.Single().Id, complete!.Version, C)).Should().ThrowAsync<DomainApplicationException>(); }

    private static readonly CancellationToken C = CancellationToken.None;
    private static (OrderManagementService Service, RestaurantDbContext Context, Branch Branch, DiningTable Table) Setup(bool admin)
    {
        var context = new RestaurantDbContext(new DbContextOptionsBuilder<RestaurantDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options); var branch = new Branch { Code = Guid.NewGuid().ToString(), Name = "Main" }; var area = new Area { BranchId = branch.Id, Name = "Ground" }; var table = new DiningTable { BranchId = branch.Id, AreaId = area.Id, TableNumber = "01", Capacity = 4 }; var product = new Product { Sku = Guid.NewGuid().ToString(), Name = "Coffee" }; context.Branches.Add(branch); context.Areas.Add(area); context.DiningTables.Add(table); context.Products.Add(product); context.BranchProducts.Add(new BranchProduct { BranchId = branch.Id, ProductId = product.Id, PriceOverride = 30000 }); context.SaveChanges(); CurrentProductId.Value = product.Id; var service = new OrderManagementService(context, new TestUser(admin), new TestAudit(), new ProductPricingService(context), new ModifierComboService(context, new TestUser(admin), new TestAudit())); return (service, context, branch, table);
    }
    private static readonly AsyncLocal<Guid> CurrentProductId = new();
    private static Guid ProductId => CurrentProductId.Value;
    private sealed class TestUser(bool admin) : ICurrentUserService { public Guid? UserId => null; public string? Username => "test"; public IReadOnlyCollection<string> Roles => []; public IReadOnlyCollection<string> Permissions => []; public Guid? BranchId => null; public bool IsAdministrator => admin; }
    private sealed class TestAudit : IAuditWriter { public Task WriteAsync(string action, string entityType, Guid? entityId, string? actorName, string? ipAddress, CancellationToken cancellationToken) => Task.CompletedTask; }
}