using Microsoft.EntityFrameworkCore;
using RestaurantManagement.Application.Common.Exceptions;
using RestaurantManagement.Application.Common.Interfaces;
using RestaurantManagement.Application.Features.Modifiers;
using RestaurantManagement.Domain.Entities;
using RestaurantManagement.Infrastructure.Persistence.DbContext;

namespace RestaurantManagement.Infrastructure.Services;

public sealed class ModifierComboService(RestaurantDbContext dbContext, ICurrentUserService currentUser, IAuditWriter auditWriter) : IModifierComboService
{
    public async Task<IReadOnlyList<ModifierGroupItem>> GetModifierGroupsAsync(CancellationToken cancellationToken) => await dbContext.ModifierGroups.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.DisplayOrder).ThenBy(x => x.Name).Select(x => new ModifierGroupItem(x.Id, x.Name, x.Description, x.SelectionType, x.MinimumSelections, x.MaximumSelections, x.IsRequired, x.DisplayOrder, x.IsActive)).ToListAsync(cancellationToken);
    public async Task<ModifierGroupDetails?> GetModifierGroupAsync(Guid id, CancellationToken cancellationToken) => await dbContext.ModifierGroups.AsNoTracking().Where(x => x.Id == id).Select(ToGroupDetails()).FirstOrDefaultAsync(cancellationToken);
    public async Task<ModifierGroupDetails> CreateModifierGroupAsync(CreateModifierGroupRequest request, CancellationToken cancellationToken)
    {
        ValidateGroup(request.MinSelections, request.MaxSelections, request.IsRequired); if (await dbContext.ModifierGroups.AnyAsync(x => x.Name == request.Name.Trim(), cancellationToken)) throw new ConflictException("A modifier group with this name already exists.");
        var group = new ModifierGroup { Name = request.Name.Trim(), Description = request.Description, SelectionType = request.SelectionType, MinimumSelections = request.MinSelections, MaximumSelections = request.MaxSelections, IsRequired = request.IsRequired, DisplayOrder = request.DisplayOrder };
        dbContext.ModifierGroups.Add(group); await auditWriter.WriteAsync("ModifierGroupCreated", nameof(ModifierGroup), group.Id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return ToGroupDetails(group);
    }
    public async Task<ModifierGroupDetails?> UpdateModifierGroupAsync(Guid id, UpdateModifierGroupRequest request, CancellationToken cancellationToken)
    {
        var group = await dbContext.ModifierGroups.FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (group is null) return null; ValidateGroup(request.MinSelections, request.MaxSelections, request.IsRequired); if (await dbContext.ModifierGroups.AnyAsync(x => x.Id != id && x.Name == request.Name.Trim(), cancellationToken)) throw new ConflictException("A modifier group with this name already exists.");
        group.Name = request.Name.Trim(); group.Description = request.Description; group.SelectionType = request.SelectionType; group.MinimumSelections = request.MinSelections; group.MaximumSelections = request.MaxSelections; group.IsRequired = request.IsRequired; group.DisplayOrder = request.DisplayOrder; await auditWriter.WriteAsync("ModifierGroupUpdated", nameof(ModifierGroup), id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return ToGroupDetails(group);
    }
    public async Task<bool> SetModifierGroupStatusAsync(Guid id, bool isActive, CancellationToken cancellationToken) { var group = await dbContext.ModifierGroups.FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (group is null) return false; group.IsActive = isActive; await auditWriter.WriteAsync(isActive ? "ModifierGroupActivated" : "ModifierGroupDeactivated", nameof(ModifierGroup), id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return true; }
    public async Task<IReadOnlyList<ModifierItem>> GetModifiersAsync(Guid groupId, CancellationToken cancellationToken) => await dbContext.Modifiers.AsNoTracking().Where(x => x.ModifierGroupId == groupId && x.IsActive).OrderBy(x => x.DisplayOrder).ThenBy(x => x.Name).Select(x => new ModifierItem(x.Id, x.ModifierGroupId, x.Name, x.Description, x.DefaultPrice, x.DisplayOrder, x.IsActive)).ToListAsync(cancellationToken);
    public async Task<ModifierDetails> CreateModifierAsync(Guid groupId, CreateModifierRequest request, CancellationToken cancellationToken)
    {
        await EnsureActiveGroupAsync(groupId, cancellationToken); if (await dbContext.Modifiers.AnyAsync(x => x.ModifierGroupId == groupId && x.Name == request.Name.Trim(), cancellationToken)) throw new ConflictException("A modifier with this name already exists in the group.");
        var modifier = new Modifier { ModifierGroupId = groupId, Name = request.Name.Trim(), Description = request.Description, DefaultPrice = request.Price, DisplayOrder = request.DisplayOrder }; dbContext.Modifiers.Add(modifier); await auditWriter.WriteAsync("ModifierCreated", nameof(Modifier), modifier.Id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return ToModifierDetails(modifier);
    }
    public async Task<ModifierDetails?> GetModifierAsync(Guid id, CancellationToken cancellationToken) => await dbContext.Modifiers.AsNoTracking().Where(x => x.Id == id).Select(ToModifierDetails()).FirstOrDefaultAsync(cancellationToken);
    public async Task<ModifierDetails?> UpdateModifierAsync(Guid id, UpdateModifierRequest request, CancellationToken cancellationToken)
    {
        var modifier = await dbContext.Modifiers.FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (modifier is null) return null; if (await dbContext.Modifiers.AnyAsync(x => x.Id != id && x.ModifierGroupId == modifier.ModifierGroupId && x.Name == request.Name.Trim(), cancellationToken)) throw new ConflictException("A modifier with this name already exists in the group.");
        modifier.Name = request.Name.Trim(); modifier.Description = request.Description; modifier.DefaultPrice = request.Price; modifier.DisplayOrder = request.DisplayOrder; await auditWriter.WriteAsync("ModifierUpdated", nameof(Modifier), id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return ToModifierDetails(modifier);
    }
    public async Task<bool> SetModifierStatusAsync(Guid id, bool isActive, CancellationToken cancellationToken) { var modifier = await dbContext.Modifiers.FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (modifier is null) return false; modifier.IsActive = isActive; await auditWriter.WriteAsync(isActive ? "ModifierActivated" : "ModifierDeactivated", nameof(Modifier), id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return true; }
    public async Task<IReadOnlyList<Guid>> GetProductModifierGroupsAsync(Guid productId, CancellationToken cancellationToken) => await dbContext.ProductModifierGroups.AsNoTracking().Where(x => x.ProductId == productId).OrderBy(x => x.DisplayOrder).Select(x => x.ModifierGroupId).ToListAsync(cancellationToken);
    public async Task<IReadOnlyList<Guid>> AssignProductModifierGroupsAsync(Guid productId, AssignModifierGroupsRequest request, CancellationToken cancellationToken)
    {
        await EnsureActiveProductAsync(productId, cancellationToken); var ids = request.ModifierGroupIds.Distinct().ToArray(); if (await dbContext.ModifierGroups.CountAsync(x => ids.Contains(x.Id) && x.IsActive, cancellationToken) != ids.Length) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("One or more modifier groups do not exist or are inactive.");
        dbContext.ProductModifierGroups.RemoveRange(await dbContext.ProductModifierGroups.Where(x => x.ProductId == productId).ToListAsync(cancellationToken)); var order = 0; foreach (var id in ids) dbContext.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = productId, ModifierGroupId = id, DisplayOrder = order++ }); await auditWriter.WriteAsync("ProductModifierGroupsChanged", nameof(Product), productId, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return ids;
    }
    public async Task ValidateSelectionsAsync(Guid productId, IReadOnlyList<ModifierSelection> selections, CancellationToken cancellationToken)
    {
        await EnsureActiveProductAsync(productId, cancellationToken); var groupIds = await dbContext.ProductModifierGroups.Where(x => x.ProductId == productId).Select(x => x.ModifierGroupId).ToListAsync(cancellationToken); if (selections.Any(x => !groupIds.Contains(x.ModifierGroupId))) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("A modifier group is not assigned to the product.");
        foreach (var groupSelection in selections)
        {
            var group = await dbContext.ModifierGroups.FirstAsync(x => x.Id == groupSelection.ModifierGroupId, cancellationToken); var ids = groupSelection.ModifierIds.Distinct().ToArray(); var modifiers = await dbContext.Modifiers.Where(x => ids.Contains(x.Id) && x.ModifierGroupId == group.Id && x.IsActive).ToListAsync(cancellationToken); if (modifiers.Count != ids.Length) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("A modifier is invalid, inactive or belongs to another group."); var count = ids.Length; if (count < group.MinimumSelections || count > group.MaximumSelections || group.IsRequired && count == 0) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException($"Modifier selection count is invalid for group {group.Name}."); if (group.SelectionType == Domain.Enums.ModifierSelectionType.Single && count > 1) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException($"Only one modifier can be selected in group {group.Name}.");
        }
        var requiredGroups = await dbContext.ModifierGroups.Where(x => groupIds.Contains(x.Id) && x.IsActive && x.IsRequired).Select(x => x.Id).ToListAsync(cancellationToken); if (requiredGroups.Any(id => selections.All(x => x.ModifierGroupId != id))) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("All required modifier groups must be selected.");
    }

    public async Task<IReadOnlyList<ComboListItem>> GetCombosAsync(CancellationToken cancellationToken) => await dbContext.Combos.AsNoTracking().Where(x => x.IsActive).OrderBy(x => x.DisplayOrder).ThenBy(x => x.Name).Select(x => new ComboListItem(x.Id, x.Code, x.Name, x.Description, x.DefaultPrice, x.DisplayOrder, x.IsActive)).ToListAsync(cancellationToken);
    public async Task<ComboDetails?> GetComboAsync(Guid id, CancellationToken cancellationToken) { var combo = await dbContext.Combos.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id, cancellationToken); return combo is null ? null : await ToComboDetailsAsync(combo, cancellationToken); }
    public async Task<ComboDetails> CreateComboAsync(CreateComboRequest request, CancellationToken cancellationToken)
    {
        if (await dbContext.Combos.AnyAsync(x => x.Code == request.Code.Trim(), cancellationToken)) throw new ConflictException("A combo with this code already exists."); await ValidateComboItemsAsync(request.Items, cancellationToken); var combo = new Combo { Code = request.Code.Trim(), Name = request.Name.Trim(), Description = request.Description, DefaultPrice = request.Price, DisplayOrder = request.DisplayOrder }; dbContext.Combos.Add(combo); AddComboItems(combo.Id, request.Items); await auditWriter.WriteAsync("ComboCreated", nameof(Combo), combo.Id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return await ToComboDetailsAsync(combo, cancellationToken);
    }
    public async Task<ComboDetails?> UpdateComboAsync(Guid id, UpdateComboRequest request, CancellationToken cancellationToken)
    {
        var combo = await dbContext.Combos.FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (combo is null) return null; if (await dbContext.Combos.AnyAsync(x => x.Id != id && x.Code == request.Code.Trim(), cancellationToken)) throw new ConflictException("A combo with this code already exists."); await ValidateComboItemsAsync(request.Items, cancellationToken); combo.Code = request.Code.Trim(); combo.Name = request.Name.Trim(); combo.Description = request.Description; combo.DefaultPrice = request.Price; combo.DisplayOrder = request.DisplayOrder; await ReplaceComboItemsAsync(id, request.Items, cancellationToken); await auditWriter.WriteAsync("ComboUpdated", nameof(Combo), id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return await ToComboDetailsAsync(combo, cancellationToken);
    }
    public async Task<bool> SetComboStatusAsync(Guid id, bool isActive, CancellationToken cancellationToken) { var combo = await dbContext.Combos.FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (combo is null) return false; if (isActive) await ValidateComboItemsAsync(await dbContext.ComboItems.Where(x => x.ComboId == id).Select(x => new ComboItemRequest(x.ProductId, x.ProductVariantId, x.Quantity, x.DisplayOrder)).ToListAsync(cancellationToken), cancellationToken); combo.IsActive = isActive; await auditWriter.WriteAsync(isActive ? "ComboActivated" : "ComboDeactivated", nameof(Combo), id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return true; }
    public async Task<ComboDetails?> ReplaceComboItemsAsync(Guid id, ComboItemUpdateRequest request, CancellationToken cancellationToken) { var combo = await dbContext.Combos.FirstOrDefaultAsync(x => x.Id == id, cancellationToken); if (combo is null) return null; await ValidateComboItemsAsync(request.Items, cancellationToken); await ReplaceComboItemsAsync(id, request.Items, cancellationToken); await auditWriter.WriteAsync("ComboItemsChanged", nameof(Combo), id, currentUser.Username, null, cancellationToken); await dbContext.SaveChangesAsync(cancellationToken); return await ToComboDetailsAsync(combo, cancellationToken); }

    private async Task EnsureActiveGroupAsync(Guid id, CancellationToken ct) { if (!await dbContext.ModifierGroups.AnyAsync(x => x.Id == id && x.IsActive, ct)) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("Modifier group does not exist or is inactive."); }
    private async Task EnsureActiveProductAsync(Guid id, CancellationToken ct) { if (!await dbContext.Products.AnyAsync(x => x.Id == id && x.IsActive, ct)) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("Product does not exist or is inactive."); }
    private static void ValidateGroup(int min, int max, bool required) { if (min < 0 || max < min || required && min < 1) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("Modifier group selection rules are invalid."); }
    private async Task ValidateComboItemsAsync(IEnumerable<ComboItemRequest> items, CancellationToken ct) { var list = items.ToList(); if (list.Count == 0) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("A combo must contain at least one item."); var products = await dbContext.Products.Where(x => list.Select(i => i.ProductId).Contains(x.Id) && x.IsActive).Select(x => x.Id).ToListAsync(ct); if (products.Count != list.Select(x => x.ProductId).Distinct().Count()) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("A combo item references an invalid product."); foreach (var item in list.Where(x => x.ProductVariantId.HasValue)) if (!await dbContext.ProductVariants.AnyAsync(x => x.Id == item.ProductVariantId && x.ProductId == item.ProductId && x.IsActive, ct)) throw new RestaurantManagement.Application.Common.Exceptions.ApplicationException("A combo variant does not belong to its product or is inactive."); if (list.GroupBy(x => new { x.ProductId, x.ProductVariantId }).Any(g => g.Count() > 1)) throw new ConflictException("A combo cannot contain duplicate product items."); }
    private void AddComboItems(Guid comboId, IEnumerable<ComboItemRequest> items) { foreach (var item in items) dbContext.ComboItems.Add(new ComboItem { ComboId = comboId, ProductId = item.ProductId, ProductVariantId = item.ProductVariantId, Quantity = item.Quantity, DisplayOrder = item.DisplayOrder }); }
    private async Task ReplaceComboItemsAsync(Guid comboId, IEnumerable<ComboItemRequest> items, CancellationToken ct) { dbContext.ComboItems.RemoveRange(await dbContext.ComboItems.Where(x => x.ComboId == comboId).ToListAsync(ct)); AddComboItems(comboId, items); }
    private async Task<ComboDetails> ToComboDetailsAsync(Combo combo, CancellationToken ct) { var items = await dbContext.ComboItems.AsNoTracking().Where(x => x.ComboId == combo.Id).OrderBy(x => x.DisplayOrder).Select(x => new ComboItemModel(x.Id, x.ComboId, x.ProductId, x.ProductVariantId, x.Quantity, x.DisplayOrder)).ToListAsync(ct); return new ComboDetails(combo.Id, combo.Code, combo.Name, combo.Description, combo.DefaultPrice, combo.DisplayOrder, combo.IsActive, items, combo.CreatedAt, combo.UpdatedAt); }
    private static System.Linq.Expressions.Expression<Func<ModifierGroup, ModifierGroupDetails>> ToGroupDetails() => x => new ModifierGroupDetails(x.Id, x.Name, x.Description, x.SelectionType, x.MinimumSelections, x.MaximumSelections, x.IsRequired, x.DisplayOrder, x.IsActive, x.CreatedAt, x.UpdatedAt);
    private static ModifierGroupDetails ToGroupDetails(ModifierGroup x) => new(x.Id, x.Name, x.Description, x.SelectionType, x.MinimumSelections, x.MaximumSelections, x.IsRequired, x.DisplayOrder, x.IsActive, x.CreatedAt, x.UpdatedAt);
    private static System.Linq.Expressions.Expression<Func<Modifier, ModifierDetails>> ToModifierDetails() => x => new ModifierDetails(x.Id, x.ModifierGroupId, x.Name, x.Description, x.DefaultPrice, x.DisplayOrder, x.IsActive, x.CreatedAt, x.UpdatedAt);
    private static ModifierDetails ToModifierDetails(Modifier x) => new(x.Id, x.ModifierGroupId, x.Name, x.Description, x.DefaultPrice, x.DisplayOrder, x.IsActive, x.CreatedAt, x.UpdatedAt);
}