using FluentAssertions;
using System.Collections.Concurrent;
using Microsoft.EntityFrameworkCore;
using RestaurantManagement.Application.Common.Exceptions;
using RestaurantManagement.Application.Common.Interfaces;
using RestaurantManagement.Application.Features.Menu;
using RestaurantManagement.Domain.Entities;
using RestaurantManagement.Infrastructure.Persistence.DbContext;
using RestaurantManagement.Infrastructure.Services;
using DomainApplicationException = RestaurantManagement.Application.Common.Exceptions.ApplicationException;

namespace RestaurantManagement.Tests.Menu;

public sealed class MenuManagementServiceTests
{
    [Fact] public async Task Create_category_succeeds() { var s = CreateService(); var r = await s.CreateCategoryAsync(new CreateCategoryRequest("Coffee", null, null, 1), C); r.Name.Should().Be("Coffee"); }
    [Fact] public async Task Get_category_returns_category() { var s = CreateService(); var r = await s.CreateCategoryAsync(new CreateCategoryRequest("Coffee", null, null, 1), C); (await s.GetCategoryAsync(r.Id, C)).Should().NotBeNull(); }
    [Fact] public async Task Update_category_changes_name() { var s = CreateService(); var r = await s.CreateCategoryAsync(new CreateCategoryRequest("Coffee", null, null, 1), C); (await s.UpdateCategoryAsync(r.Id, new UpdateCategoryRequest("Tea", "hot drinks", null, 2), C))!.Name.Should().Be("Tea"); }
    [Fact] public async Task Deactivate_category_excludes_it_from_list() { var s = CreateService(); var r = await s.CreateCategoryAsync(new CreateCategoryRequest("Coffee", null, null, 1), C); await s.SetCategoryStatusAsync(r.Id, false, C); (await s.GetCategoriesAsync(C)).Should().BeEmpty(); }
    [Fact] public void Invalid_category_is_rejected_by_validator() { new CreateCategoryValidator().Validate(new CreateCategoryRequest("", null, null, -1)).IsValid.Should().BeFalse(); }

    [Fact] public async Task Create_product_succeeds() { var s = CreateService(); var r = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", "drink", "Hot coffee", 1, []), C); r.Sku.Should().Be("CF001"); }
    [Fact] public async Task Duplicate_product_sku_is_rejected() { var s = CreateService(); await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await FluentActions.Awaiting(() => s.CreateProductAsync(new CreateProductRequest("CF001", "Tea", null, null, 2, []), C)).Should().ThrowAsync<ConflictException>(); }
    [Fact] public async Task Get_product_returns_product() { var s = CreateService(); var r = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); (await s.GetProductAsync(r.Id, C)).Should().NotBeNull(); }
    [Fact] public async Task Update_product_changes_name() { var s = CreateService(); var r = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); (await s.UpdateProductAsync(r.Id, new UpdateProductRequest("CF001", "Iced Coffee", null, null, 1, []), C))!.Name.Should().Be("Iced Coffee"); }
    [Fact] public async Task Deactivate_product_excludes_it_from_list() { var s = CreateService(); var r = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await s.SetProductStatusAsync(r.Id, false, C); (await s.GetProductsAsync(C)).Should().BeEmpty(); }

    [Fact] public async Task Assign_category_to_product_succeeds() { var s = CreateService(); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); (await s.AssignCategoriesAsync(p.Id, new AssignCategoriesRequest([c.Id]), C))!.CategoryIds.Should().Contain(c.Id); }
    [Fact] public async Task Duplicate_category_assignment_is_collapsed() { var s = CreateService(); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id, c.Id]), C); p.CategoryIds.Should().ContainSingle(); }
    [Fact] public async Task Missing_category_assignment_is_rejected() { var s = CreateService(); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await FluentActions.Awaiting(() => s.AssignCategoriesAsync(p.Id, new AssignCategoriesRequest([Guid.NewGuid()]), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Multiple_categories_are_supported() { var s = CreateService(); var c1 = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var c2 = await s.CreateCategoryAsync(new CreateCategoryRequest("Hot", null, null, 2), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c1.Id, c2.Id]), C); p.CategoryIds.Should().HaveCount(2); }
    [Fact] public async Task Inactive_category_cannot_be_assigned() { var s = CreateService(); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); await s.SetCategoryStatusAsync(c.Id, false, C); await FluentActions.Awaiting(() => s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id]), C)).Should().ThrowAsync<DomainApplicationException>(); }

    [Fact] public async Task Create_variant_succeeds() { var s = CreateService(); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); (await s.CreateVariantAsync(p.Id, new CreateVariantRequest("Large", "CF001-L", 30000, 1), C)).Name.Should().Be("Large"); }
    [Fact] public async Task Variant_requires_existing_product() { var s = CreateService(); await FluentActions.Awaiting(() => s.CreateVariantAsync(Guid.NewGuid(), new CreateVariantRequest("Large", null, 1, 1), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public void Negative_variant_price_is_rejected_by_validator() { new CreateVariantValidator().Validate(new CreateVariantRequest("Large", null, -1, 1)).IsValid.Should().BeFalse(); }
    [Fact] public async Task Update_variant_changes_price() { var s = CreateService(); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); var v = await s.CreateVariantAsync(p.Id, new CreateVariantRequest("Large", null, 30000, 1), C); (await s.UpdateVariantAsync(v.Id, new UpdateVariantRequest("Large", null, 35000, 1), C))!.Price.Should().Be(35000); }
    [Fact] public async Task Deactivate_variant_excludes_it_from_active_variants() { var s = CreateService(); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); var v = await s.CreateVariantAsync(p.Id, new CreateVariantRequest("Large", null, 30000, 1), C); await s.SetVariantStatusAsync(v.Id, false, C); (await s.GetVariantsAsync(p.Id, C)).Should().BeEmpty(); }

    [Fact] public async Task Create_primary_image_succeeds() { var s = CreateService(); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); (await s.CreateImageAsync(p.Id, new CreateProductImageRequest("https://cdn.test/coffee.jpg", "Coffee", 1, true), C)).IsPrimary.Should().BeTrue(); }
    [Fact] public async Task Only_one_primary_image_is_kept() { var s = CreateService(); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await s.CreateImageAsync(p.Id, new CreateProductImageRequest("one", null, 1, true), C); await s.CreateImageAsync(p.Id, new CreateProductImageRequest("two", null, 2, true), C); (await s.GetImagesAsync(p.Id, C)).Count(x => x.IsPrimary).Should().Be(1); }
    [Fact] public async Task Deleting_image_soft_deactivates_it() { var s = CreateService(); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); var i = await s.CreateImageAsync(p.Id, new CreateProductImageRequest("one", null, 1, false), C); await s.DeleteImageAsync(i.Id, C); (await s.GetImagesAsync(p.Id, C)).Should().BeEmpty(); }

    [Fact] public async Task Create_branch_product_succeeds() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); (await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C)).Price.Should().Be(30000); }
    [Fact] public async Task Duplicate_branch_product_is_rejected() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); await FluentActions.Awaiting(() => s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 32000, true), C)).Should().ThrowAsync<ConflictException>(); }
    [Fact] public async Task Unauthorized_branch_product_is_rejected() { var s = CreateService(new TestCurrentUser { IsAdministratorValue = false }); var b = await CreateBranchAsync(s, "B001"); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await FluentActions.Awaiting(() => s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C)).Should().ThrowAsync<ForbiddenException>(); }
    [Fact] public async Task Same_product_can_exist_in_two_branches() { var s = CreateService(); var b1 = await CreateBranchAsync(s, "B001"); var b2 = await CreateBranchAsync(s, "B002"); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await s.CreateBranchProductAsync(b1.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); (await s.CreateBranchProductAsync(b2.Id, new CreateBranchProductRequest(p.Id, 35000, true), C)).BranchId.Should().Be(b2.Id); }
    [Fact] public async Task Branch_prices_are_independent() { var s = CreateService(); var b1 = await CreateBranchAsync(s, "B001"); var b2 = await CreateBranchAsync(s, "B002"); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); await s.CreateBranchProductAsync(b1.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); await s.CreateBranchProductAsync(b2.Id, new CreateBranchProductRequest(p.Id, 40000, true), C); (await s.GetBranchProductsAsync(b2.Id, C)).Single().Price.Should().Be(40000); }
    [Fact] public async Task Branch_product_availability_can_be_toggled() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, []), C); var bp = await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); (await s.SetBranchProductAvailabilityAsync(bp.Id, false, C))!.IsAvailable.Should().BeFalse(); }
    [Fact] public async Task Negative_branch_price_is_rejected_by_validator() { new CreateBranchProductValidator().Validate(new CreateBranchProductRequest(Guid.NewGuid(), -1, true)).IsValid.Should().BeFalse(); }

    [Fact] public async Task Active_menu_returns_available_product() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id]), C); await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); (await s.GetMenuAsync(b.Id, C)).Categories.SelectMany(x => x.Products).Should().ContainSingle(); }
    [Fact] public async Task Inactive_product_is_excluded_from_menu() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id]), C); await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); await s.SetProductStatusAsync(p.Id, false, C); (await s.GetMenuAsync(b.Id, C)).Categories.Should().BeEmpty(); }
    [Fact] public async Task Unavailable_branch_product_is_excluded_from_menu() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id]), C); await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, false), C); (await s.GetMenuAsync(b.Id, C)).Categories.Should().BeEmpty(); }
    [Fact] public async Task Inactive_category_is_excluded_from_menu() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id]), C); await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); await s.SetCategoryStatusAsync(c.Id, false, C); (await s.GetMenuAsync(b.Id, C)).Categories.Should().BeEmpty(); }
    [Fact] public async Task Inactive_variant_is_excluded_from_menu() { var s = CreateService(); var b = await CreateBranchAsync(s, "B001"); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id]), C); await s.CreateBranchProductAsync(b.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); var v = await s.CreateVariantAsync(p.Id, new CreateVariantRequest("Large", null, 35000, 1), C); await s.SetVariantStatusAsync(v.Id, false, C); (await s.GetMenuAsync(b.Id, C)).Categories.SelectMany(x => x.Products).Single().Variants.Should().BeEmpty(); }
    [Fact] public async Task Menu_is_branch_isolated() { var s = CreateService(); var b1 = await CreateBranchAsync(s, "B001"); var b2 = await CreateBranchAsync(s, "B002"); var c = await s.CreateCategoryAsync(new CreateCategoryRequest("Drinks", null, null, 1), C); var p = await s.CreateProductAsync(new CreateProductRequest("CF001", "Coffee", null, null, 1, [c.Id]), C); await s.CreateBranchProductAsync(b1.Id, new CreateBranchProductRequest(p.Id, 30000, true), C); (await s.GetMenuAsync(b2.Id, C)).Categories.Should().BeEmpty(); }

    private static readonly CancellationToken C = CancellationToken.None;
    private static readonly ConcurrentDictionary<MenuManagementService, RestaurantDbContext> Contexts = new();
    private static async Task<Branch> CreateBranchAsync(MenuManagementService service, string code) { var context = Contexts[service]; var branch = new Branch { Code = code, Name = code }; context.Branches.Add(branch); await context.SaveChangesAsync(); return branch; }
    private static MenuManagementService CreateService(TestCurrentUser? user = null) { var context = GetContext(); var service = new MenuManagementService(context, user ?? new TestCurrentUser(), new TestAuditWriter()); Contexts[service] = context; return service; }
    private static RestaurantDbContext GetContext() => new(new DbContextOptionsBuilder<RestaurantDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);

    private sealed class TestCurrentUser : ICurrentUserService { public bool IsAdministratorValue { get; init; } = true; public Guid? UserId => null; public string? Username => "test"; public IReadOnlyCollection<string> Roles => []; public IReadOnlyCollection<string> Permissions => []; public Guid? BranchId => null; public bool IsAdministrator => IsAdministratorValue; }
    private sealed class TestAuditWriter : IAuditWriter { public Task WriteAsync(string action, string entityType, Guid? entityId, string? actorName, string? ipAddress, CancellationToken cancellationToken) => Task.CompletedTask; }
}