using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using RestaurantManagement.Application.Common.Exceptions;
using RestaurantManagement.Application.Common.Interfaces;
using RestaurantManagement.Application.Features.Modifiers;
using RestaurantManagement.Application.Features.Pricing;
using RestaurantManagement.Domain.Entities;
using RestaurantManagement.Domain.Enums;
using RestaurantManagement.Infrastructure.Persistence.DbContext;
using RestaurantManagement.Infrastructure.Services;
using DomainApplicationException = RestaurantManagement.Application.Common.Exceptions.ApplicationException;

namespace RestaurantManagement.Tests.Modifiers;

public sealed class ModifierComboServiceTests
{
    [Fact] public async Task Create_group() { var (s, _) = Setup(); (await s.CreateModifierGroupAsync(Group("Toppings"), C)).Name.Should().Be("Toppings"); }
    [Fact] public async Task Get_group() { var (s, _) = Setup(); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); (await s.GetModifierGroupAsync(g.Id, C)).Should().NotBeNull(); }
    [Fact] public async Task Update_group() { var (s, _) = Setup(); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); (await s.UpdateModifierGroupAsync(g.Id, GroupUpdate("Extras"), C))!.Name.Should().Be("Extras"); }
    [Fact] public async Task Deactivate_group() { var (s, _) = Setup(); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); await s.SetModifierGroupStatusAsync(g.Id, false, C); (await s.GetModifierGroupsAsync(C)).Should().BeEmpty(); }
    [Fact] public async Task Duplicate_group_name_rejected() { var (s, _) = Setup(); await s.CreateModifierGroupAsync(Group("Toppings"), C); await FluentActions.Awaiting(() => s.CreateModifierGroupAsync(Group("Toppings"), C)).Should().ThrowAsync<ConflictException>(); }
    [Fact] public void Invalid_group_range() => new CreateModifierGroupValidator().Validate(new CreateModifierGroupRequest("x", null, ModifierSelectionType.Multiple, 3, 1, false, 0)).IsValid.Should().BeFalse();
    [Fact] public void Required_group_needs_minimum() => new CreateModifierGroupValidator().Validate(new CreateModifierGroupRequest("x", null, ModifierSelectionType.Single, 0, 1, true, 0)).IsValid.Should().BeFalse();
    [Fact] public async Task Create_modifier() { var (s, _) = Setup(); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); (await s.CreateModifierAsync(g.Id, Modifier("Pearl", 5000), C)).Name.Should().Be("Pearl"); }
    [Fact] public async Task Modifier_requires_group() { var (s, _) = Setup(); await FluentActions.Awaiting(() => s.CreateModifierAsync(Guid.NewGuid(), Modifier("Pearl", 5000), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public void Negative_modifier_price() => new CreateModifierValidator().Validate(new CreateModifierRequest("x", null, -1, 0)).IsValid.Should().BeFalse();
    [Fact] public void Negative_modifier_update_price() => new UpdateModifierValidator().Validate(new UpdateModifierRequest("x", null, -1, 0)).IsValid.Should().BeFalse();
    [Fact] public async Task Update_modifier() { var (s, _) = Setup(); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); var m = await s.CreateModifierAsync(g.Id, Modifier("Pearl", 5000), C); (await s.UpdateModifierAsync(m.Id, new UpdateModifierRequest("Pearl", null, 7000, 1), C))!.Price.Should().Be(7000); }
    [Fact] public async Task Deactivate_modifier() { var (s, _) = Setup(); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); var m = await s.CreateModifierAsync(g.Id, Modifier("Pearl", 5000), C); await s.SetModifierStatusAsync(m.Id, false, C); (await s.GetModifiersAsync(g.Id, C)).Should().BeEmpty(); }
    [Fact] public async Task Assign_group_to_product() { var (s, c) = Setup(); var p = Product(c); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); (await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g.Id]), C)).Should().Contain(g.Id); }
    [Fact] public async Task Duplicate_assignment_is_collapsed() { var (s, c) = Setup(); var p = Product(c); var g = await s.CreateModifierGroupAsync(Group("Toppings"), C); (await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g.Id, g.Id]), C)).Should().ContainSingle(); }
    [Fact] public async Task Invalid_assignment_rejected() { var (s, c) = Setup(); var p = Product(c); await FluentActions.Awaiting(() => s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([Guid.NewGuid()]), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Valid_single_selection() { var (s, c) = Setup(); var (p, g, m) = await ProductWithModifierAsync(s, c, ModifierSelectionType.Single, 1, 1); await s.ValidateSelectionsAsync(p, [new ModifierSelection(g, [m])], C); }
    [Fact] public async Task Too_many_single_selection_rejected() { var (s, c) = Setup(); var p = Product(c); var g = await s.CreateModifierGroupAsync(new CreateModifierGroupRequest("Size", null, ModifierSelectionType.Single, 1, 1, true, 0), C); var m1 = await s.CreateModifierAsync(g.Id, Modifier("S", 1), C); var m2 = await s.CreateModifierAsync(g.Id, Modifier("M", 2), C); await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g.Id]), C); await FluentActions.Awaiting(() => s.ValidateSelectionsAsync(p.Id, [new ModifierSelection(g.Id, [m1.Id, m2.Id])], C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Too_few_selection_rejected() { var (s, c) = Setup(); var p = Product(c); var g = await s.CreateModifierGroupAsync(new CreateModifierGroupRequest("T", null, ModifierSelectionType.Multiple, 1, 3, true, 0), C); await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g.Id]), C); await FluentActions.Awaiting(() => s.ValidateSelectionsAsync(p.Id, [], C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Required_group_missing_rejected() { var (s, c) = Setup(); var p = Product(c); var g = await s.CreateModifierGroupAsync(new CreateModifierGroupRequest("T", null, ModifierSelectionType.Single, 1, 1, true, 0), C); await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g.Id]), C); await FluentActions.Awaiting(() => s.ValidateSelectionsAsync(p.Id, [], C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Modifier_from_wrong_group_rejected() { var (s, c) = Setup(); var p = Product(c); var g1 = await s.CreateModifierGroupAsync(Group("A"), C); var g2 = await s.CreateModifierGroupAsync(Group("B"), C); var m = await s.CreateModifierAsync(g2.Id, Modifier("x", 1), C); await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g1.Id]), C); await FluentActions.Awaiting(() => s.ValidateSelectionsAsync(p.Id, [new ModifierSelection(g1.Id, [m.Id])], C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Inactive_modifier_rejected() { var (s, c) = Setup(); var p = Product(c); var g = await s.CreateModifierGroupAsync(Group("A"), C); var m = await s.CreateModifierAsync(g.Id, Modifier("x", 1), C); await s.SetModifierStatusAsync(m.Id, false, C); await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g.Id]), C); await FluentActions.Awaiting(() => s.ValidateSelectionsAsync(p.Id, [new ModifierSelection(g.Id, [m.Id])], C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public void Negative_combo_price_rejected() => new CreateComboValidator().Validate(new CreateComboRequest("C", "Combo", null, -1, 0, [])).IsValid.Should().BeFalse();
    [Fact] public async Task Group_not_assigned_rejected() { var (s, c) = Setup(); var p = Product(c); var g = await s.CreateModifierGroupAsync(Group("A"), C); var m = await s.CreateModifierAsync(g.Id, Modifier("x", 1), C); await FluentActions.Awaiting(() => s.ValidateSelectionsAsync(p.Id, [new ModifierSelection(g.Id, [m.Id])], C)).Should().ThrowAsync<DomainApplicationException>(); }

    [Fact] public async Task Base_price_calculated() { var (s, c) = Setup(); var b = Branch(c); var p = Product(c); c.BranchProducts.Add(new BranchProduct { BranchId = b.Id, ProductId = p.Id, PriceOverride = 30000 }); await c.SaveChangesAsync(); (await new ProductPricingService(c).CalculateAsync(new ProductPricingRequest(p.Id, null, b.Id, []), C)).FinalUnitPrice.Should().Be(30000); }
    [Fact] public async Task Variant_price_calculated() { var (s, c) = Setup(); var b = Branch(c); var p = Product(c); var v = new ProductVariant { ProductId = p.Id, Name = "L", DefaultPrice = 35000 }; c.ProductVariants.Add(v); c.BranchProducts.Add(new BranchProduct { BranchId = b.Id, ProductId = p.Id, PriceOverride = 30000 }); await c.SaveChangesAsync(); (await new ProductPricingService(c).CalculateAsync(new ProductPricingRequest(p.Id, v.Id, b.Id, []), C)).FinalUnitPrice.Should().Be(35000); }
    [Fact] public async Task Modifier_price_added() { var (s, c) = Setup(); var b = Branch(c); var p = Product(c); var g = new ModifierGroup { Name = "T", MaximumSelections = 2 }; var m = new Modifier { ModifierGroupId = g.Id, Name = "x", DefaultPrice = 5000 }; c.ModifierGroups.Add(g); c.Modifiers.Add(m); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = p.Id, ModifierGroupId = g.Id }); c.BranchProducts.Add(new BranchProduct { BranchId = b.Id, ProductId = p.Id, PriceOverride = 30000 }); await c.SaveChangesAsync(); (await new ProductPricingService(c).CalculateAsync(new ProductPricingRequest(p.Id, null, b.Id, [m.Id]), C)).FinalUnitPrice.Should().Be(35000); }
    [Fact] public async Task Multiple_modifier_prices_added() { var (s, c) = Setup(); var b = Branch(c); var p = Product(c); var g = new ModifierGroup { Name = "T", MaximumSelections = 3 }; var m1 = new Modifier { ModifierGroupId = g.Id, Name = "x", DefaultPrice = 5000 }; var m2 = new Modifier { ModifierGroupId = g.Id, Name = "y", DefaultPrice = 10000 }; c.ModifierGroups.Add(g); c.Modifiers.AddRange(m1, m2); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = p.Id, ModifierGroupId = g.Id }); c.BranchProducts.Add(new BranchProduct { BranchId = b.Id, ProductId = p.Id, PriceOverride = 30000 }); await c.SaveChangesAsync(); (await new ProductPricingService(c).CalculateAsync(new ProductPricingRequest(p.Id, null, b.Id, [m1.Id, m2.Id]), C)).ModifierTotal.Should().Be(15000); }
    [Fact] public async Task Zero_price_modifier_supported() { var (s, c) = Setup(); var b = Branch(c); var p = Product(c); var g = new ModifierGroup { Name = "T", MaximumSelections = 1 }; var m = new Modifier { ModifierGroupId = g.Id, Name = "free", DefaultPrice = 0 }; c.ModifierGroups.Add(g); c.Modifiers.Add(m); c.ProductModifierGroups.Add(new ProductModifierGroup { ProductId = p.Id, ModifierGroupId = g.Id }); c.BranchProducts.Add(new BranchProduct { BranchId = b.Id, ProductId = p.Id, PriceOverride = 30000 }); await c.SaveChangesAsync(); (await new ProductPricingService(c).CalculateAsync(new ProductPricingRequest(p.Id, null, b.Id, [m.Id]), C)).FinalUnitPrice.Should().Be(30000); }
    [Fact] public async Task Unavailable_product_pricing_rejected() { var (s, c) = Setup(); var b = Branch(c); var p = Product(c); c.BranchProducts.Add(new BranchProduct { BranchId = b.Id, ProductId = p.Id, PriceOverride = 30000, IsAvailable = false }); await c.SaveChangesAsync(); await FluentActions.Awaiting(() => new ProductPricingService(c).CalculateAsync(new ProductPricingRequest(p.Id, null, b.Id, []), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Invalid_variant_pricing_rejected() { var (s, c) = Setup(); var b = Branch(c); var p = Product(c); c.BranchProducts.Add(new BranchProduct { BranchId = b.Id, ProductId = p.Id, PriceOverride = 30000 }); await c.SaveChangesAsync(); await FluentActions.Awaiting(() => new ProductPricingService(c).CalculateAsync(new ProductPricingRequest(p.Id, Guid.NewGuid(), b.Id, []), C)).Should().ThrowAsync<DomainApplicationException>(); }

    [Fact] public async Task Create_combo() { var (s, c) = Setup(); var p = Product(c); var combo = await s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(p.Id, null, 1, 1)]), C); combo.Code.Should().Be("C001"); }
    [Fact] public async Task Duplicate_combo_code_rejected() { var (s, c) = Setup(); var p = Product(c); await s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(p.Id, null, 1, 1)]), C); await FluentActions.Awaiting(() => s.CreateComboAsync(new CreateComboRequest("C001", "Other", null, 70000, 1, [new ComboItemRequest(p.Id, null, 1, 1)]), C)).Should().ThrowAsync<ConflictException>(); }
    [Fact] public async Task Invalid_combo_product_rejected() { var (s, _) = Setup(); await FluentActions.Awaiting(() => s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(Guid.NewGuid(), null, 1, 1)]), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Variant_product_mismatch_rejected() { var (s, c) = Setup(); var p1 = Product(c); var p2 = Product(c); var v = new ProductVariant { ProductId = p2.Id, Name = "L", DefaultPrice = 1 }; c.ProductVariants.Add(v); await c.SaveChangesAsync(); await FluentActions.Awaiting(() => s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(p1.Id, v.Id, 1, 1)]), C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public void Combo_quantity_validator_rejects_zero() => new ComboItemValidator().Validate(new ComboItemRequest(Guid.NewGuid(), null, 0, 0)).IsValid.Should().BeFalse();
    [Fact] public async Task Update_combo_items() { var (s, c) = Setup(); var p1 = Product(c); var p2 = Product(c); var combo = await s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(p1.Id, null, 1, 1)]), C); (await s.ReplaceComboItemsAsync(combo.Id, new ComboItemUpdateRequest([new ComboItemRequest(p2.Id, null, 1, 1)]), C))!.Items.Single().ProductId.Should().Be(p2.Id); }
    [Fact] public async Task Deactivate_combo() { var (s, c) = Setup(); var p = Product(c); var combo = await s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(p.Id, null, 1, 1)]), C); await s.SetComboStatusAsync(combo.Id, false, C); (await s.GetCombosAsync(C)).Should().BeEmpty(); }
    [Fact] public async Task Combo_cannot_activate_with_inactive_item() { var (s, c) = Setup(); var p = Product(c); var combo = await s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(p.Id, null, 1, 1)]), C); p.IsActive = false; await c.SaveChangesAsync(); await FluentActions.Awaiting(() => s.SetComboStatusAsync(combo.Id, true, C)).Should().ThrowAsync<DomainApplicationException>(); }
    [Fact] public async Task Duplicate_combo_items_rejected() { var (s, c) = Setup(); var p = Product(c); await FluentActions.Awaiting(() => s.CreateComboAsync(new CreateComboRequest("C001", "Meal", null, 70000, 1, [new ComboItemRequest(p.Id, null, 1, 1), new ComboItemRequest(p.Id, null, 1, 2)]), C)).Should().ThrowAsync<ConflictException>(); }

    private static readonly CancellationToken C = CancellationToken.None;
    private static (ModifierComboService Service, RestaurantDbContext Context) Setup() { var context = new RestaurantDbContext(new DbContextOptionsBuilder<RestaurantDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options); return (new ModifierComboService(context, new TestUser(), new TestAudit()), context); }
    private static Product Product(RestaurantDbContext c) { var p = new Product { Sku = Guid.NewGuid().ToString(), Name = "Product" }; c.Products.Add(p); c.SaveChanges(); return p; }
    private static Branch Branch(RestaurantDbContext c) { var b = new Branch { Code = Guid.NewGuid().ToString(), Name = "Branch" }; c.Branches.Add(b); c.SaveChanges(); return b; }
    private static CreateModifierGroupRequest Group(string name) => new(name, null, ModifierSelectionType.Multiple, 0, 3, false, 0);
    private static UpdateModifierGroupRequest GroupUpdate(string name) => new(name, null, ModifierSelectionType.Multiple, 0, 3, false, 0);
    private static CreateModifierRequest Modifier(string name, decimal price) => new(name, null, price, 0);
    private static async Task<(Guid ProductId, Guid GroupId, Guid ModifierId)> ProductWithModifierAsync(ModifierComboService s, RestaurantDbContext c, ModifierSelectionType type, int min, int max) { var p = Product(c); var g = await s.CreateModifierGroupAsync(new CreateModifierGroupRequest("G", null, type, min, max, min > 0, 0), C); var m = await s.CreateModifierAsync(g.Id, Modifier("M", 1), C); await s.AssignProductModifierGroupsAsync(p.Id, new AssignModifierGroupsRequest([g.Id]), C); return (p.Id, g.Id, m.Id); }
    private sealed class TestUser : ICurrentUserService { public Guid? UserId => null; public string? Username => "test"; public IReadOnlyCollection<string> Roles => []; public IReadOnlyCollection<string> Permissions => []; public Guid? BranchId => null; public bool IsAdministrator => true; }
    private sealed class TestAudit : IAuditWriter { public Task WriteAsync(string action, string entityType, Guid? entityId, string? actorName, string? ipAddress, CancellationToken cancellationToken) => Task.CompletedTask; }
}